site_name: pod-charlesreid1
docs_dir: docs
site_dir: site
theme:
  name: null
  custom_dir: 'mkdocs-material/material'
  palette:
    primary: 'green'
    accent: 'green'
  logo:
    icon: 'bug report'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
extra_css:
  - css/custom.css
pages:
  - 'Index' : 'index.md'
